name: Python CI/CD Pipeline

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        # Upgrade pip and install core application dependencies
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        # Install testing tools
        pip install pytest pytest-cov coverage

    - name: Run Tests and Generate Coverage Report
      # CRITICAL FIX: Change directory (cd) into the tests folder and 
      # run pytest using the python interpreter flag (-m pytest).
      # The '--cov=..' tells coverage to look up one level (at the root) 
      # for the modules (app.py and models.py).
      run: |
        cd tests
        python -m pytest -q --cov=.. --cov-report=xml --cov-report=term

    - name: Upload Coverage Report (Codecov)
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true

    - name: Notify on Failure
      if: failure()
      run: echo "Tests failed! Check the run logs for  details."
